theme = "everforest_dark"
# theme = "papercolor-light"

[editor]
line-number = "relative"
mouse = true
scrolloff = 6
scroll-lines = 1
cursorline = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[keys.insert]
A-h = "move_char_left"
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_char_right"
